### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException - on Windows

### ISSUE THREAD

**Issue by sardetushar** [melanio/codecheese-blog-examples#1]
I tried your both the code but getting null pointer error.

https://github.com/melanio/codecheese-blog-examples/blob/master/orc-examples/src/main/java/codecheese/blog/examples/orc/SimpleOrcWriterUsingVectorizedRowBatch.java

https://github.com/melanio/codecheese-blog-examples/blob/master/orc-examples/src/main/java/codecheese/blog/examples/orc/OrcWriterUsingVectorizedRowBatch.java

**Comment by melanio** [comment]
Interesting.  I recloned the project and everything ran fine for me.
Can you provide the stacktrace?
By any chance are you running on Windows?

**Comment by sardetushar** [comment]
Hello Melanio! thanks for your response. Yes I am running on windows and I had to set hadoop home path in my code. we should have winutils.exe inside D:/hadoop/bin/ folder

`System.setProperty("hadoop.home.dir", "D:/hadoop");`

Code is working now!
